### PR TITLE
Support for PLP Varchar

### PR DESCRIPTION
**Pull request by agalakhov**
Tested and seems to work.
NB: I left NChar handling as-is, but looks like there is something wrong with NULL values, isn't it?

### CODE REVIEW

**Comment by steffengy** [comment]
What do you mean something is wrong with handling null values?

For NULL values with PLP size=0xffffffffffffffff (PLP_NULL) is sent, see MS-TDS 2.2.5.2.3 "Partially Length-prefixed Bytes" section), does that answer what you meant?

Also could you add 
```rust
 #[test]
    fn test_big_varchar() {
        let future = SqlConnection::connect(connection_string().as_ref()).and_then(|conn| 
            conn.simple_query("select replicate(cast('4' as varchar(max)), 127420)").for_each(|row| {
                assert_eq!(row.get::<_, Option<&str>>(0), None);
                Ok(())
            })
        );
        current_thread::block_on_all(future).unwrap();
    }
```
as a testcase for it?

**Comment by agalakhov** [comment]
The PLP code for NULL is fine.
However, there is NChar code which does not use PLP but shares the same reading engine. It was implemented by `if *len < 0xfff || *ty = VarLenType::NChar` which is suspicious since it does not have NULL branch at all. I guess 0xffff means NULL in this case, but I did not check MSDN for it yet.

**Comment by steffengy** [comment]
`0xffff` is the length of the used datatype (not the data!) passed in the COLMETADATA token. `0xffff` there indicates that the type is `VARCHAR(MAX)`, which is encoded via PLP.
Then the actual length of the data is read.
In case of PLP 64bit, if it was not `VARCHAR(MAX)`, only 16bit.
thats the other control flow branch that is there currently

Let me know if that makes sense/is clear.

**Comment by agalakhov** [comment]
It is not clear how NULL for NVarchar/NChar for sizes up to 0x8000 is handled. The corresponding branch https://github.com/steffengy/tiberius/pull/62#issuecomment-395918364 never returns `ColumnData::None`.

**Comment by steffengy** [comment]
Yep thats right, that afaik only isn't an issue (but yes it's missing) because the server decides to encode NULL values as PLP anyways.

**Comment by agalakhov** [comment]
Yes, for (N)VarChar it isn't. But it seems to be one for NChar, since `if *len < 0xfff || *ty = VarLenType::NChar` always goes to the non-PLP branch in this case.

**Comment by steffengy** [comment]
Agreed

**Comment by steffengy** [comment]
@agalakhov Looks good so far, thanks very much for this!
Anything else you'd like addressed before a merge?

**Comment by agalakhov** [comment]
Thank you! Now one could easily add `Varbin` as well since it's almost the same.

**Comment by steffengy** [comment]
Yeah Varbin is probably easy, on the long term getting nvarchar ported to this is more interesting, since it's very commonly used and I'd like to have one implementation for them, but for now I think landing this and then looking into those points separately makes sense.

**Comment by agalakhov** [comment]
It's already done in this pull request! NVarchar and Varchar share the same code now. The very first commit, 70851eb, does exactly that.

**Comment by steffengy** [comment]
Oh right, yeah, I missed that part in the bottom.
So I'll change that plan towards changing to measure how it performs^^
Even greater!

**Pull request merged**
