### PR TITLE
Add possibility to get column names and to iterate over columns

### PR DESCRIPTION
**Pull request by agalakhov**
Also removed debugging println!().

### CODE REVIEW

**Comment by steffengy** [comment]
I'd personally prefer to simply expose `columns` similar to how postgres is doing that:
https://docs.rs/postgres/0.15.1/postgres/rows/struct.Rows.html#method.columns

Iterating over that then either works by directly using a for-loop or calling .iter()/.into_iter() on the slice.

Any issues/disadvantages doing that?

**Comment by agalakhov** [comment]
No disadvantages, but names and values are in two separate arrays, so we can't just take a slice.
What I did works like
```
for column in &row {
    let n = column.name();
    let v: String = column.get();
    println!("{} = {}". n, v);
}
```
which is almost the same as iterating over row.columns().
We can also add a convenience method `columns()` which does just the same as `into_iter()` for the referene.

**Comment by steffengy** [comment]
Sorry for taking so long.

I'm not a fan of directly introducing `name` on `Row`.

I think returning a `Column` (new type) and making the iterator iterate over `(column, row)`
would be better design-wise, how do you feel about that?
It would allow easily exposing new fields, while not giving name a special position.

**Comment by agalakhov** [comment]
Why not? This would mean just throwing away the `name(idx)` function of `Row` and leaving only the `Column::name()`. The rest won't change. For symmetry, one can introduce `Column::index()` as well.

**Comment by steffengy** [comment]
> Why not? 

Because we might want to expose more column-specific functionality later (type, or whatever)
which leads to more functions which don't quite fit into `Row` semantically.
They'd atleast need a `column_` prefix, which is more to type.

Moving that into `Column` seems good therefore.

Maybe it's better to just introduce a `columns` function which returns a `Vec<Columns>`.
Then the iterator would just return the column values and we could do:

```rust
let columns = row.columns();
for (column, val) in row.into_iter().zip(columns.iter()) { ... }
```

**Comment by agalakhov** [comment]
There is such a function in `Column` already. It is currently duplicated in `Row`, but the duplicate could easily be removed.

**Comment by steffengy** [comment]
I don't quite get what you're refering to since `Column` does not exist yet?

**Comment by agalakhov** [comment]
It's named `QueryRowItem` in my commit, but renaming it to `Column` would be just fine.

**Comment by steffengy** [comment]
No, `Column` would only contain meta informations about a column
but no reference to a query row whatsoever.

`QueryRowItem` wouldn't be necessary since the iterator should only return column-data
(not sure if that part is feasible, but thats the direction I'm currently thinking about).

**Comment by agalakhov** [comment]
Why not? A column is got from `Row`, that is, it contains one and only value. Making it contain only the metadata allows for erratic use of a column with another row. Semantically we have now:
* A result set consists of query stream.
* A query stream consists of rows.
* A row consists of (name, value) pairs.
What's the reason to split these pairs? Or do you want to make the `columns()` method in `QueryStream` instead of `QueryRow`, that is, common to all rows?

**Comment by steffengy** [comment]
Well there's a bit of a flaw in my logic.

Since the rows are returned at the beginning of a query (before any rows are returned),
I hoped to "save" an ARC by tieing the metadata to the QueryStream (technically also tricky).
But the metadata is already ARC-counted through `TokenRow.meta`.

So I still think of something like:
- add `QueryRow::columns()` which returns a TokenRow.meta.columns wrapper (e.g. access to name)
- add `QueryRow::into_iter()` which returns an iterator with `ColumnData` as item.

The reason is that you can access columndata without any unnecessary meta-overhead
(e.g. if you only want to read some columns and dont care about the meta information).
If you need the meta information, you can "opt-in" for it this way.

Is that a bit clearer and are there still some objections or issues?

**Comment by agalakhov** [comment]
In such an architecture it should be `QueryStream::columns()`. Like a table caption. We read the caption first, then we iterate over columns.

**Comment by steffengy** [comment]
That wouldn't be ergonomic at all.
It also makes sense that rows refer to columns, because without that meta information
the data in the row would be useless.

**Comment by agalakhov** [comment]
And that's why I want the row to be like `[(name, value)]`. It protects against use of wrong columns with the data. If columns aren't global for the entire table, they aren't columns. They are cells.

For ergonomic reasons I want to have a simple way to iterate over (name, value) pairs. For safety reasons I don't want it to be like `zip(row.names.iter(), row,values.iter())` to avoid zipping with something else.

There is an use-case of having global column metainformation for the whole table. It's finding columns by names. For performance reasons it's better to resolve names to indices first, then iterate over rows using numeric indices. It is especially important since the current algorithm of name resolution is O(n) search. If it runs for each row in a huge table, it will be really slow.

Also, a GUI is likely to show column names only in caption, so for a GUI it's better to have global column names. This does not mean that each row can't reference the global metainfo. No `Arc` is needed here, just a scoped reference with an appropriate lifetime.

**Comment by steffengy** [comment]
> And that's why I want the row to be like [(name, value)]. It protects against use of wrong columns with the data.

It doesn't. If internally something goes wrong or a user decides to use a wrong numeric index,
you'll still use the wrong data.

> If columns aren't global for the entire table, they aren't columns. They are cells.

Yes columns are always global for an entire table.

> For ergonomic reasons I want to have a simple way to iterate over (name, value) pairs. For safety reasons I don't want it to be like zip(row.names.iter(), row,values.iter()) to avoid zipping with something else.

Adding an alias e.g. `enumerate` that returns the zip would compensate for that.

> There is an use-case of having global column metainformation for the whole table. It's finding columns by names. For performance reasons it's better to resolve names to indices first, then iterate over rows using numeric indices. It is especially important since the current algorithm of name resolution is O(n) search. If it runs for each row in a huge table, it will be really slow.

The column meta information is global. You still need a reference to each row though,
because else a user cannot get a column by name automagically. Since the DB is anyways
IO-bound it shouldn't matter for most usecases, but yes it scales with the amount of columns.

> Also, a GUI is likely to show column names only in caption, so for a GUI it's better to have global column names. This does not mean that each row can't reference the global metainfo. No Arc is needed here, just a scoped reference with an appropriate lifetime.

In that case you'd just call `.columns()` on the first row.

> This does not mean that each row can't reference the global metainfo. No Arc is needed here, just a scoped reference with an appropriate lifetime.

That doesn't work in an async model.

**Comment by agalakhov** [comment]
> Yes columns are always global for an entire table.

The API does not reflect this fact (yet). Yes, it's obvious from the SQL semantics, but we're talking about the Rust API. If `.columns()` is a property of `Row`, it looks misleading since it looks like `.columns()` are row-local.

> In that case you'd just call .columns() on the first row.

How do I know that the return value of `.columns()` is always the same? How do I know that reusing `.columns()` from one row for the next row(s) is safe?

For me, if there is a method like `a.foo()` and `b.foo()`, I expect that `foo` MAY differ for `a` and `b` and I won't reuse the value of `a.foo()` for `b` in safe code. If they share the same value, I expect something like `a.get_parent().foo()` instead.

> That doesn't work in an async model.

One could make it work since the whole table exists longer than one row even in futures model. Just a bit tricky.

**Comment by steffengy** [comment]
> The API does not reflect this fact (yet). Yes, it's obvious from the SQL semantics, but we're talking about the Rust API. If .columns() is a property of Row, it looks misleading since it looks like .columns() are row-local. At least it could mean that the .columns() call clones the values.

Well e.g. the postgres driver, which I'd argue is the most stable rust database driver, [does the same thing](https://docs.rs/postgres/0.15.1/postgres/rows/struct.Row.html).  
I think it's really clear that all that `columns()` does is return the associated columns of the row 
(which by definition are the columns of the executed statement):

> QuerySteam::columns() - returns table column names and types

I'd like that too honestly, I just don't see how that would work.
The meta information is just not available that soon which would leave us with more bloat
like
```rust
impl QueryStream { fn columns() -> impl Future<Item=QueryStreamWithMeta> }
impl QueryStreamWithMeta { fn poll() {...} }
```
It just isn't practical.

> How do I know that the return value of .columns() is always the same? How do I know that reusing .columns() from one row for the next row(s) is safe?

By definition. A comment on the `columns()` function would make this even clearer.

> One could make it work [..]

No you cannot, since a future could in theory be executed in a threadpool, which
would require a `'static` lifetime (or ARC) which a scoped lifetime cannot fullfil.

**Comment by agalakhov** [comment]
> I'd like that too honestly, I just don't see how that would work.

We could resolve getting of `QueryStream` itself only when the metainformation is available. Without metadata is is useless anyway.

Ok, there is another question: why not alias column name as a property of each item? Iterating over `QueryRow` must return `Item` with `.get<T>() -> T` and `.try_get<T>() -> Result` methods since the types may vary. Adding extra methods like `.type() -> ...` or `.name() -> &str` here seems to be harmless.

> No you cannot, since a future could in theory be executed in a threadpool

Is it `Send` now?

**Comment by steffengy** [comment]
> We could resolve getting of QueryStream itself only when the metainformation is available. Without metadata is is useless anyway.

My bad, that should actually even be the case.

> Ok, there is another question: why not alias column name as a property of each item? Iterating over QueryRow must return Item with .get<T>() -> T and .try_get<T>() -> Result methods since the types may vary. Adding extra methods like .type() -> ... or .name() -> &str here seems to be harmless.

You mean an iterator with `ColumnValue` as item which wraps `Column` and the value for that row
and would have methods like `type()`, `name()` etc. That sounds okay.

> Is it Send now?
If "it" refers to the `QueryStream`, then yes (it should actually even be Send + Sync + 'static as required)

**Comment by schultyy** [comment]
Is this still being worked on? That feature would come in handy in a project of mine

**Comment by brokenthorn** [comment]
What's the current way of getting the column names, not from the results stream, if that seems to be not possible at the moment?

> No, `Column` would only contain meta informations about a column
> but no reference to a query row whatsoever.
> 
> `QueryRowItem` wouldn't be necessary since the iterator should only return column-data
> (not sure if that part is feasible, but thats the direction I'm currently thinking about).

I agree! That's by far the most popular implementation in similar libraries. It would make `tiberius` easier to understand for newcomers.

**Comment by brokenthorn** [comment]
> That wouldn't be ergonomic at all.
> It also makes sense that rows refer to columns, because without that meta information
> the data in the row would be useless.

Could you have the column meta information attached to the `QueryResult` (query stream), maybe `QueryResult::columns() -> Arc<Vec<Column>>`, and maybe not encourage column meta information to be accessed in row iterators which would be more runtime overhead?

And if you need the column name in row iterators, you just need to use the same index you use for the `QueryIdx` on `get()` or `try_get()`, to read from the `Vec<Column>`.

Oh, by the way, the documentation for `QueryIdx` says it's for getting specific rows even though it's used to get columns as well.

**Comment by steffengy** [comment]
Access to column names will be in 0.4.
The runtime overhead is negligible compared to the rest involved.

**Pull request closed without merging**
