### PR TITLE
Add support for Cow<'a, str> in ToSql

### PR DESCRIPTION
**Pull request by danylaporte**
Allow to send Cow<'a, str>, and string as ToSql.

### CODE REVIEW

**Comment by steffengy** [comment]
Any case where this is needed?
Cow<'a, str> should already deref to &str?

**Comment by danylaporte** [comment]
I need this to be able to send an owned string. I have implement a trait to be able to convert from a struct to sql parameters. The problem is with lifetime.

**Comment by steffengy** [comment]
Whats the issue with something like the following?

```rust
let s: String = "test".to_owned();
        let future =
            SqlConnection::connect(connection_string().as_ref()).and_then(|conn| {
                conn.query("select @P1", &[&s.as_str()])
                    .for_each(|row| {
                        assert_eq!(row.get::<_, &str>(0), "test");
                        Ok(())
                    })
            });
        current_thread::block_on_all(future).unwrap();
```

**Comment by danylaporte** [comment]
Here is a sample code of the code I want to achieve.
```rust
trait ToParameter {
    fn to_parameter(&self) -> Parameter;
}

enum Parameter<'a> {
    Str(&'a str),
    String(String),
}

impl<'a> From<&'a Parameter<'a>> for &'a ToSql {
    fn from(d: &'a Parameter<'a>) -> &'a ToSql {
        match d {
            Parameter::Str(v) => v,
            Parameter::String(v) => v.as_str(),  // <- cannot compile this
        }
    }
}
```
I have my own implementation over Tiberius that allows me to convert "serialize/deserialize" my own struct from columns.

Things like Json coming from a string in database can be automatically serialize / deserialize from the database.
```rust
#[derive(Serialize)]
struct MyOwnComplexFieldType;

/// serialize MyOwnComplexTypeField into the database.
impl ToParameter for MyOwnComplexFieldType {
   fn to_parameter(&self) -> Parameter {
      let s = ::serde_json::to_str(self).expect("serialize");
      Parameter::String(s)
   }
}
```

**Comment by steffengy** [comment]
Yeah seems like this is the fastest solution.
Just wanted to make sure I understand the usecase, maybe in future versions I'll figure something out.
Thanks!

**Comment by danylaporte** [comment]
Thanks to you for merging my pull request but also for this wonderful crate.

**Pull request merged**
